[package]
name = "equs-vcx-did-parser-nom"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
description = "DID and DID URL parser built with nom"
repository = "https://github.com/equs-ai/vcx"

[lib]
name = "did_parser_nom"

[dependencies]
nom = "7.1.3"
serde = "1.0.160"
log = "0.4.16"
percent-encoding = "2"

[dev-dependencies]
serde_test = "1.0.176"
env_logger = "0.11.3"
