[package]
name = "equs-vcx-public-key"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
description = "Public key types with multibase and multicodec conversions"
repository = "https://github.com/equs-ai/vcx"

[lib]
name = "public_key"

[features]
jwk = ["dep:askar-crypto"]

[dependencies]
thiserror = "1.0.40"
serde = { version = "1.0.164", features = ["derive"] }
serde_json = "1.0.96"
base64 = "0.22.1"
bs58 = "0.5.0"
multibase = "=0.9.2"
unsigned-varint = "0.8.0"
# askar-crypto used for jwk conversion. maintain minimal feature set
askar-crypto = { workspace = true, features = [
    "std",
    "any_key",
    "ec_curves",
    "ed25519",
], optional = true }
