[package]
name = "equs-vcx-did-resolver"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
description = "DID resolution traits and types"
repository = "https://github.com/equs-ai/vcx"

[lib]
name = "did_resolver"

[features]
default = []

[dependencies]
did_parser_nom = { package = "equs-vcx-did-parser-nom", version = "0.1.0", path = "../did_parser_nom" }
did_doc = { package = "equs-vcx-did-doc", version = "0.1.0", path = "../did_doc" }
async-trait = "0.1.68"
chrono = { version = "0.4.24", default-features = false, features = ["serde", "alloc"] }
serde = { version = "1.0.160", default-features = false, features = ["derive"] }
serde_json = "1.0.103"
typed-builder = "0.19.1"
